import { Data } from "./types";

export const dummyData: Data[] = [
  {
    firstName: "John",
    lastName: "Doe",
    age: 28,
    birthdate: new Date("1992-04-10"),
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    region: "Jiangxi",
    city: "Ganzhou",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    age: 32,
    birthdate: new Date("1992-04-10"),
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    region: "Kurskaya Oblast",
    city: "Kursk",
  },
  {
    firstName: "Alice",
    lastName: "Smith",
    age: 24,
    birthdate: new Date("1999-01-22"),
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026705d",
    region: "California",
    city: "San Francisco",
  },
  {
    firstName: "Bob",
    lastName: "Brown",
    age: 31,
    birthdate: new Date("1991-05-19"),
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026706d",
    region: "New South Wales",
    city: "Sydney",
  },
  {
    firstName: "Carol",
    lastName: "Johnson",
    age: 29,
    birthdate: new Date("1994-03-15"),
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026707d",
    region: "Quebec",
    city: "Montreal",
  },
  {
    firstName: "David",
    lastName: "Wilson",
    age: 34,
    birthdate: new Date("1989-07-30"),
    avatar: "https://i.pravatar.cc/150?img=15",
    region: "Bavaria",
    city: "Munich",
  },
  {
    firstName: "Eva",
    lastName: "Martinez",
    age: 27,
    birthdate: new Date("1996-02-11"),
    avatar: "https://i.pravatar.cc/150?img=21",
    region: "Andalusia",
    city: "Seville",
  },
  {
    firstName: "Frank",
    lastName: "Garcia",
    age: 30,
    birthdate: new Date("1993-08-23"),
    avatar: "https://i.pravatar.cc/150?img=22",
    region: "Saxony",
    city: "Dresden",
  },
  {
    firstName: "Grace",
    lastName: "Lee",
    age: 26,
    birthdate: new Date("1997-12-12"),
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026711d",
    region: "Tokyo",
    city: "Tokyo",
  },
  {
    firstName: "Henry",
    lastName: "Davis",
    age: 35,
    birthdate: new Date("1988-04-05"),
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026712d",
    region: "Illinois",
    city: "Chicago",
  },
  {
    firstName: "Isla",
    lastName: "Miller",
    age: 22,
    birthdate: new Date("2001-06-18"),
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026713d",
    region: "Ontario",
    city: "Toronto",
  },
  {
    firstName: "Jack",
    lastName: "Taylor",
    age: 33,
    birthdate: new Date("1990-02-25"),
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026714d",
    region: "Greater London",
    city: "London",
  },
  {
    firstName: "Kara",
    lastName: "Anderson",
    age: 25,
    birthdate: new Date("1998-08-09"),
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026715d",
    region: "Stockholm County",
    city: "Stockholm",
  },
  {
    firstName: "Liam",
    lastName: "Thomas",
    age: 29,
    birthdate: new Date("1994-01-20"),
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026716d",
    region: "Île-de-France",
    city: "Paris",
  },
  {
    firstName: "Mia",
    lastName: "Harris",
    age: 28,
    birthdate: new Date("1995-03-30"),
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026717d",
    region: "New York",
    city: "New York",
  },
  {
    firstName: "Noah",
    lastName: "Martin",
    age: 31,
    birthdate: new Date("1992-07-11"),
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026718d",
    region: "Berlin",
    city: "Berlin",
  },
  {
    firstName: "Olivia",
    lastName: "White",
    age: 24,
    birthdate: new Date("1999-05-21"),
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026719d",
    region: "Catalonia",
    city: "Barcelona",
  },
  {
    firstName: "Peter",
    lastName: "Clark",
    age: 32,
    birthdate: new Date("1991-10-13"),
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026720d",
    region: "Moscow",
    city: "Moscow",
  },
  {
    firstName: "Quinn",
    lastName: "Rodriguez",
    age: 27,
    birthdate: new Date("1996-04-18"),
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026721d",
    region: "Maharashtra",
    city: "Mumbai",
  },
  {
    firstName: "Ruby",
    lastName: "Lewis",
    age: 30,
    birthdate: new Date("1993-11-08"),
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026722d",
    region: "Victoria",
    city: "Melbourne",
  },
  {
    firstName: "Sam",
    lastName: "Walker",
    age: 26,
    birthdate: new Date("1997-07-23"),
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026723d",
    region: "Queensland",
    city: "Brisbane",
  },
  {
    firstName: "Tina",
    lastName: "Allen",
    age: 34,
    birthdate: new Date("1989-02-14"),
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026724d",
    region: "Beijing Municipality",
    city: "Beijing",
  },
];

export const fields = [
  {
    name: "firstName",
    label: "First Name",
    placeholder: 'Value',
    operators: [
      { name: "=", label: "Equals" },
      { name: "!=", label: "Not equal" },
      { name: "contains", label: "contains" },
      { name: "begins with", label: "begins with" },
      { name: "ends with", label: "ends with" },
      { name: "does not contain", label: "does not contain" },
      { name: "does not begin with", label: "does not begin with" },
      { name: "does not end with", label: "does not end with" },
    ],
  },
  {
    name: "lastName",
    label: "Last Name",
    placeholder: 'Value',
    operators: [
      { name: "=", label: "Equals" },
      { name: "!=", label: "Not equal" },
      { name: "contains", label: "contains" },
      { name: "begins with", label: "begins with" },
      { name: "ends with", label: "ends with" },
      { name: "does not contain", label: "does not contain" },
      { name: "does not begin with", label: "does not begin with" },
      { name: "does not end with", label: "does not end with" },
    ],
  },
  {
    name: "age",
    label: "Age",
    placeholder: 'Value',
    operators: [
      { name: "=", label: "Equals" },
      { name: "!=", label: "Not equal" },
      { name: ">", label: "Greater than" },
      { name: ">=", label: "Greather than or equal to" },
      { name: "<", label: "Less than" },
      { name: "<=", label: "Less than or equal to" },
    ],
  },
  {
    name: "birthdate",
    label: "Birthdate",
    inputType: "date",
    operators: [
      { name: "=", label: "Equals" },
      { name: "!=", label: "Not equal" },
      { name: ">", label: "Greater than" },
      { name: ">=", label: "Greather than or equal to" },
      { name: "<", label: "Less than" },
      { name: "<=", label: "Less than or equal to" },
    ],
  },
  {
    name: "region",
    label: "Region",
    placeholder: 'Value',
    operators: [
      { name: "=", label: "Equals" },
      { name: "!=", label: "Not equal" },
      { name: "contains", label: "contains" },
      { name: "begins with", label: "begins with" },
      { name: "ends with", label: "ends with" },
      { name: "does not contain", label: "does not contain" },
      { name: "does not begin with", label: "does not begin with" },
      { name: "does not end with", label: "does not end with" },
    ],
  },
  {
    name: "city",
    label: "City",
    placeholder: 'Value',
    operators: [
      { name: "=", label: "Equals" },
      { name: "!=", label: "Not equal" },
      { name: "contains", label: "contains" },
      { name: "begins with", label: "begins with" },
      { name: "ends with", label: "ends with" },
      { name: "does not contain", label: "does not contain" },
      { name: "does not begin with", label: "does not begin with" },
      { name: "does not end with", label: "does not end with" },
    ],
  },
];
